# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2020-06-26 04:50
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taskApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('not_started', 'Not started'), ('inprogress', 'Inprogress'), ('done', 'Done')], default='not_started', max_length=30)),
                ('created_by', models.CharField(blank=True, max_length=50)),
                ('created_on', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
                ('assign_to', models.ManyToManyField(blank=True, related_name='tasks_many', related_query_name='q_task', to=settings.AUTH_USER_MODEL)),
                ('worker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', related_query_name='task', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
